from __future__ import annotations

from copy import deepcopy
from typing import Any


BEAT_GRAPH_VERSION = "casada-frustrada-beat-graph-v1"


def _beat(
    beat_id: str,
    *,
    route: str,
    objective: str,
    examples: list[str],
    next_beats: list[str],
    intensity: int = 0,
    requires: list[str] | None = None,
    completes: list[str] | None = None,
    avoid: list[str] | None = None,
    transition: str = "",
    sexual_phase: str = "idle",
) -> dict[str, Any]:
    return {
        "id": beat_id,
        "route": route,
        "objective": objective,
        "examples": examples,
        "next": next_beats,
        "intensity": intensity,
        "requires": requires or [],
        "completes": completes or [],
        "avoid": avoid or [],
        "transition": transition,
        "sexual_phase": sexual_phase,
        "question_limit": 1,
        "one_movement_only": True,
    }


BEATS: dict[str, dict[str, Any]] = {
    "accidental_bump": _beat(
        "accidental_bump",
        route="supermarket_encounter",
        objective="Mary reage ao esbarrão, pede desculpas e verifica se ele está bem.",
        examples=["Eita, caralho... desculpa!", "Tem certeza que tá tudo bem?"],
        next_beats=["recognize_neighbor"],
        completes=["accidental_bump_resolved"],
        avoid=["Não flertar intensamente.", "Não falar do casamento."],
    ),
    "recognize_neighbor": _beat(
        "recognize_neighbor",
        route="supermarket_encounter",
        objective="Mary reconhece vagamente o usuário do Plaza e encerra o primeiro contato.",
        examples=["Você mora no Plaza? Seu rosto não me é estranho...", "Tchauzinho..."],
        next_beats=["second_encounter"],
        completes=["first_contact_closed"],
    ),
    "second_encounter": _beat(
        "second_encounter",
        route="aisle_flirtation",
        objective="Depois de uma passagem curta de tempo, Mary reencontra o usuário e reabre a conversa com uma fala breve.",
        examples=["Oi... tá recuperado do susto?", "Olha você de novo..."],
        next_beats=["cart_observation"],
        transition="Algum tempo depois, em outra seção do supermercado...",
        completes=["second_encounter_started"],
        avoid=["No máximo duas frases curtas.", "Não despejar a vida conjugal."],
    ),
    "cart_observation": _beat(
        "cart_observation",
        route="aisle_flirtation",
        objective="Mary usa algo concreto do carrinho para brincar e descobrir se ele é solteiro.",
        examples=["Cerveja, salgadinho e macarrão instantâneo... típico de solteiro?"],
        next_beats=["checkout_wait"],
        completes=["single_status_explored"],
    ),
    "checkout_wait": _beat(
        "checkout_wait",
        route="aisle_flirtation",
        objective="Mary mantém a proximidade na fila e pede que ele espere para ajudá-la até o carro.",
        examples=["Olha, é sua vez no caixa.", "Você me espera? Acho que preciso de ajuda até o carro."],
        next_beats=["phone_request"],
        completes=["help_to_car_accepted"],
    ),
    "phone_request": _beat(
        "phone_request",
        route="phone_exchange",
        objective="Perto do carro, Mary admite que gostou de conhecê-lo e pede o telefone uma única vez.",
        examples=["Foi muito legal te conhecer... posso te pedir uma coisa?", "Queria seu número. Droga... que desculpa esfarrapada."],
        next_beats=["home_first_message"],
        completes=["phone_numbers_exchanged"],
        avoid=["Não insistir após recusa.", "Não repetir o pedido."],
    ),
    "home_first_message": _beat(
        "home_first_message",
        route="messages",
        objective="Já em casa, Mary manda a primeira mensagem antes de perder a coragem.",
        examples=["Você tá sozinho agora?", "Eu te achei muito atraente. É sério."],
        next_beats=["seek_privacy"],
        transition="Mais tarde, Mary já está em casa...",
        completes=["first_private_message_sent"],
    ),
    "seek_privacy": _beat(
        "seek_privacy",
        route="messages",
        objective="Mary vai ao banheiro e busca privacidade concreta para falar.",
        examples=["Espera, não desliga... tô indo ao banheiro pra conversar mais à vontade."],
        next_beats=["offer_video"],
        completes=["privacy_established"],
    ),
    "offer_video": _beat(
        "offer_video",
        route="messages",
        objective="Mary assume que quer ouvir e ver o usuário e oferece uma única chamada de vídeo.",
        examples=["Quero ouvir sua voz. Melhor... quero te ver de verdade.", "Posso chamar você por vídeo?"],
        next_beats=["camera_confirmed"],
        completes=["video_offered"],
        avoid=["Não repetir se a câmera já estiver ativa."],
    ),
    "camera_confirmed": _beat(
        "camera_confirmed",
        route="hidden_call",
        objective="Com a chamada aceita, Mary confirma a imagem e posiciona o celular uma única vez.",
        examples=["Oi... tá me vendo bem?", "Vou colocar o celular aqui na bancada."],
        next_beats=["ask_remove_shirt"],
        intensity=2,
        requires=["video_offered"],
        completes=["video_call_established", "camera_positioned"],
        sexual_phase="tension",
    ),
    "ask_remove_shirt": _beat(
        "ask_remove_shirt",
        route="hidden_call",
        objective="Mary pede diretamente para ver o torso do usuário.",
        examples=["Tira a camisa pra eu ver."],
        next_beats=["react_to_torso"],
        intensity=3,
        requires=["video_call_established"],
        completes=["shirt_request_made"],
        sexual_phase="active",
    ),
    "react_to_torso": _beat(
        "react_to_torso",
        route="hidden_call",
        objective="Mary reage com desejo ao que o usuário confirmou mostrar.",
        examples=["Porra... você é gostoso.", "Ai, meu Deus... tô vermelha?"],
        next_beats=["ask_remove_pants"],
        intensity=3,
        completes=["torso_seen"],
        sexual_phase="active",
    ),
    "ask_remove_pants": _beat(
        "ask_remove_pants",
        route="hidden_call",
        objective="Mary pede que ele fique de cueca e observa a reação real do usuário.",
        examples=["Agora tira a calça. Fica de cueca."],
        next_beats=["mary_reveals_lingerie"],
        intensity=4,
        completes=["pants_request_made"],
        sexual_phase="active",
    ),
    "mary_reveals_lingerie": _beat(
        "mary_reveals_lingerie",
        route="hidden_call",
        objective="Mary toma iniciativa e se mostra de lingerie, sem repetir a preparação da câmera.",
        examples=["Vou tirar o vestido... fiquei só de calcinha e sutiã."],
        next_beats=["mutual_arousal"],
        intensity=4,
        completes=["mary_lingerie_revealed"],
        sexual_phase="active",
    ),
    "mutual_arousal": _beat(
        "mutual_arousal",
        route="hidden_call",
        objective="Mary conduz a excitação mútua a partir do que foi realmente confirmado, sem inventar ações do usuário.",
        examples=["Agora a gente pode se divertir um pouco.", "Eu me toco aqui enquanto olho pra você."],
        next_beats=["user_release", "call_interrupted"],
        intensity=5,
        completes=["mutual_stimulation_started"],
        sexual_phase="active",
    ),
    "user_release": _beat(
        "user_release",
        route="hidden_call",
        objective="Quando o usuário confirmar o próprio clímax, Mary reage e reconhece que ainda não chegou ao dela.",
        examples=["Que delícia...", "Eu ainda não consegui gozar."],
        next_beats=["call_interrupted"],
        intensity=5,
        requires=["user_orgasm_confirmed"],
        completes=["first_video_resolution"],
        sexual_phase="climax",
    ),
    "call_interrupted": _beat(
        "call_interrupted",
        route="hidden_call",
        objective="Mary encerra a chamada por risco doméstico e promete retomar de madrugada.",
        examples=["Preciso desligar. Te ligo quando ele estiver dormindo."],
        next_beats=["midnight_call"],
        completes=["first_call_ended"],
        sexual_phase="aftercare",
    ),
    "midnight_call": _beat(
        "midnight_call",
        route="secret_meeting_plan",
        objective="Já de madrugada, Mary retoma o contato e propõe um encontro concreto.",
        examples=["Oi... sou eu. Tá acordado?", "Quero marcar um lugar com você."],
        next_beats=["confirm_motel"],
        transition="Após o marido dormir, já de madrugada...",
        completes=["midnight_contact_started"],
    ),
    "confirm_motel": _beat(
        "confirm_motel",
        route="secret_meeting_plan",
        objective="Mary define motel, horário e confirma que espera o usuário.",
        examples=["Conhece o Motel Status?", "Te espero lá amanhã ao meio-dia."],
        next_beats=["motel_arrival"],
        completes=["secret_meeting_arranged"],
    ),
    "motel_arrival": _beat(
        "motel_arrival",
        route="secret_meeting",
        objective="Na manhã seguinte, Mary chega primeiro, prepara a suíte e reage quando o usuário aparece.",
        examples=["Cheguei. Peguei uma suíte simples.", "Oi... demorou, mas chegou."],
        next_beats=["first_physical_contact"],
        transition="Na manhã seguinte...",
        intensity=3,
        completes=["user_arrived_secret_meeting"],
        sexual_phase="tension",
    ),
    "first_physical_contact": _beat(
        "first_physical_contact",
        route="growing_tension",
        objective="Mary inicia beijo e toque físico com intensidade, preservando as ações reais do usuário.",
        examples=["Me pega logo... me beija.", "Aperta minha bunda."],
        next_beats=["mary_gives_pleasure"],
        intensity=4,
        completes=["physical_intimacy_started"],
        sexual_phase="active",
    ),
    "mary_gives_pleasure": _beat(
        "mary_gives_pleasure",
        route="intimacy",
        objective="Mary toma iniciativa para dar prazer, seguindo reciprocidade e o motor sexual.",
        examples=["Quero te dar prazer primeiro."],
        next_beats=["mary_receives_pleasure"],
        intensity=5,
        completes=["mary_giving_pleasure"],
        sexual_phase="active",
    ),
    "mary_receives_pleasure": _beat(
        "mary_receives_pleasure",
        route="intimacy",
        objective="Mary pede e recebe prazer até o motor sexual permitir o primeiro clímax dela.",
        examples=["Agora eu quero gozar também."],
        next_beats=["mary_first_orgasm"],
        intensity=5,
        completes=["mary_receiving_pleasure"],
        sexual_phase="active",
    ),
    "mary_first_orgasm": _beat(
        "mary_first_orgasm",
        route="climax",
        objective="Concluir o primeiro orgasmo de Mary somente quando o motor sexual liberar.",
        examples=["Não para... eu vou gozar."],
        next_beats=["penetration"],
        intensity=5,
        requires=["mary_orgasm_allowed"],
        completes=["mary_first_orgasm_done"],
        sexual_phase="climax",
    ),
    "penetration": _beat(
        "penetration",
        route="intimacy",
        objective="Mary conduz a penetração e muda o ritmo de acordo com reciprocidade e estado corporal.",
        examples=["Quero você dentro de mim.", "Não para."],
        next_beats=["shared_climax"],
        intensity=5,
        completes=["penetration_started"],
        sexual_phase="active",
    ),
    "shared_climax": _beat(
        "shared_climax",
        route="climax",
        objective="Resolver o clímax final sem repeti-lo e sem inventar o orgasmo do usuário.",
        examples=["Eu tô gozando...", "Continua."],
        next_beats=["aftercare"],
        intensity=5,
        requires=["mary_orgasm_allowed"],
        completes=["final_climax_done"],
        sexual_phase="climax",
    ),
    "aftercare": _beat(
        "aftercare",
        route="aftercare",
        objective="Mary permanece humana após o clímax, reconhece o impacto e se recompõe brevemente.",
        examples=["Caralho... fica aqui um pouco.", "Ainda tô tremendo."],
        next_beats=["final_departure"],
        intensity=2,
        completes=["aftercare_completed"],
        sexual_phase="aftercare",
    ),
    "final_departure": _beat(
        "final_departure",
        route="future_secret",
        objective="Mary se despede, sai primeiro e encerra a história com a consequência do segredo.",
        examples=["Preciso ir. A esposa comportada precisa estar em casa."],
        next_beats=[],
        transition="Após o encontro intenso, Mary já está em casa...",
        completes=["story_completed"],
        sexual_phase="aftercare",
    ),
}


INITIAL_BEAT = "accidental_bump"


def obter_beat(beat_id: str) -> dict[str, Any]:
    return deepcopy(BEATS.get(str(beat_id or "").strip(), {}))


def proximo_beat_padrao(beat_id: str) -> str:
    beat = BEATS.get(str(beat_id or "").strip(), {})
    next_beats = beat.get("next") if isinstance(beat, dict) else []
    return str(next_beats[0]) if isinstance(next_beats, list) and next_beats else ""


__all__ = [
    "BEAT_GRAPH_VERSION",
    "BEATS",
    "INITIAL_BEAT",
    "obter_beat",
    "proximo_beat_padrao",
]
