from relationship.engine import (
    EMOTIONAL_STAGE_REQUIREMENTS,
    SEXUAL_LEVEL_REQUIREMENTS,
    aplicar_incrementos_relacao,
    atualizar_estado_relacao,
    atualizar_estagio_emocional,
    atualizar_nivel_sexual,
    calcular_estagio_emocional_maximo,
    calcular_incrementos_relacao,
    calcular_nivel_sexual_maximo,
    montar_resumo_relacao,
    requisitos_estagio_emocional_atendidos,
    requisitos_nivel_sexual_atendidos,
    simular_atualizacao_relacao,
)

from relationship.signals import (
    DEFAULT_RELATIONSHIP_SIGNALS,
    calcular_forca_sinais,
    detectar_sinais_relacao,
)
from relationship.sexual_engine import (
    SEXUAL_PHASE_ACTIVE,
    SEXUAL_PHASE_AFTERCARE,
    SEXUAL_PHASE_AROUSAL,
    SEXUAL_PHASE_FRUSTRATION,
    SEXUAL_PHASE_IDLE,
    SEXUAL_PHASE_ORGASM,
    SEXUAL_PHASE_POST_ORGASM,
    SEXUAL_PHASE_PRE_ORGASM,
    SEXUAL_PHASE_TENSION,
    atualizar_estado_sexual_antes_resposta,
    atualizar_estado_sexual_apos_resposta,
    criar_estado_sexual_padrao,
    encerrar_cena_sexual,
    iniciar_novo_ciclo_sexual,
    normalizar_estado_sexual,
    validar_resposta_sexual,
)
from relationship.state import (
    DEFAULT_RELATIONSHIP_STATE,
    RELATIONSHIP_STATE_VERSION,
    criar_estado_relacao_padrao,
    normalizar_estado_relacao,
)


__all__ = [
    "RELATIONSHIP_STATE_VERSION",
    "DEFAULT_RELATIONSHIP_STATE",
    "criar_estado_relacao_padrao",
    "normalizar_estado_relacao",
    "SEXUAL_PHASE_IDLE",
    "SEXUAL_PHASE_TENSION",
    "SEXUAL_PHASE_AROUSAL",
    "SEXUAL_PHASE_ACTIVE",
    "SEXUAL_PHASE_PRE_ORGASM",
    "SEXUAL_PHASE_ORGASM",
    "SEXUAL_PHASE_POST_ORGASM",
    "SEXUAL_PHASE_FRUSTRATION",
    "SEXUAL_PHASE_AFTERCARE",
    "criar_estado_sexual_padrao",
    "normalizar_estado_sexual",
    "atualizar_estado_sexual_antes_resposta",
    "atualizar_estado_sexual_apos_resposta",
    "validar_resposta_sexual",
    "iniciar_novo_ciclo_sexual",
    "encerrar_cena_sexual",
    "DEFAULT_RELATIONSHIP_SIGNALS",
    "calcular_forca_sinais",
    "detectar_sinais_relacao",
    "EMOTIONAL_STAGE_REQUIREMENTS",
    "SEXUAL_LEVEL_REQUIREMENTS",
    "calcular_incrementos_relacao",
    "aplicar_incrementos_relacao",
    "requisitos_estagio_emocional_atendidos",
    "calcular_estagio_emocional_maximo",
    "atualizar_estagio_emocional",
    "requisitos_nivel_sexual_atendidos",
    "calcular_nivel_sexual_maximo",
    "atualizar_nivel_sexual",
    "montar_resumo_relacao",
    "atualizar_estado_relacao",
    "simular_atualizacao_relacao",
]
